on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: mvn --batch-mode test --settings settings.xml

       
      #- name: Maven build
        #run: mvn --file pom.xml package
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy to Github Package Registry
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        #run: mvn --settings settings.xml --file pom.xml deploy
        run: mvn --batch-mode --update-snapshots package
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#************************************************************************

  #Docker:
    #name: push Docker image
    #runs-on: ubuntu-latest
    #needs: [test]
    #permissions:
      #packages: write
      #contents: read
    #steps:
      #- name: Ckeck out repo
       # uses: actions/checkout@v3

      #- name: Log in to Docker Hub
        #uses: docker/login-action@v2
        #with:
          #username: ${{ secrets.USER_DOCKER }}
          #password: ${{ secrets.PASSWORD_DOCKER }}

      #- name: Build and push
        #run: docker build -t juandiaz9102/image-nginx:tag .

      #- run: docker push juandiaz9102/image-nginx:tag