on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: mvn --batch-mode test --settings settings.xml

      #- name: Maven build
        #run: mvn --file pom.xml package
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        
  publish-artifact-build_image:
    runs-on: ubuntu-latest
    needs: [Test]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Maven Settings for deploy
        uses: s4u/maven-settings-action@v2.1.1
      - name: Publish package
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: mvn deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/juandiaz9102/micro-service'

  Docker:
    name: push Docker image
    runs-on: ubuntu-latest
    needs: [test, publish-artifact-build_image]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Ckeck out repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USSER_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      #- name: Build and push
        #run: docker build -t juandiaz9102/image-nginx:tag .

      #- run: docker push juandiaz9102/image-nginx:tag


  