on:
  push:
    branches:
      - main

     
jobs:
  test:                                                         # test no tiene error    
    runs-on: ubuntu-latest                                      #
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: mvn --batch-mode test --settings settings.xml

      #- name: Maven build
        #run: mvn --file pom.xml package
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #build:
    #runs-on: ubuntu-latest
    
    #steps:
      #- uses: actions/checkout@v1
      #- name: Set up JDK 11
        #uses: actions/setup-java@v1
        #with:
          #java-version: 11
      #- name: Maven build
        #run: mvn --file pom.xml package

  #publish-artifact-build_image:
    #runs-on: ubuntu-latest
    #needs: [Test-sonar]
    #permissions:
      #contents: read
      #packages: write
    #steps:
      #- uses: actions/checkout@v2
      #- uses: actions/setup-java@v2
        #with:
          #java-version: '11'
          #distribution: 'adopt'
      #- name: Set up Maven Settings for deploy
        #uses: s4u/maven-settings-action@v2.1.1
      #- name: Publish package
        #env:
          #USER_NAME: ${{ secrets.USER_NAME }}
          #TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        #run: mvn deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/juandiaz9102/micro-service'
        #run: mvn --batch-mode --update-snapshots package
        #run: mvn --settings settings.xml --file pom.xml deploy
##########################################################################  

  #deploy:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- name: Set up JDK 11
        #uses: actions/setup-java@v2
        #with:
          #java-version: 11
          #distribution: 'adopt'
      #- name: Deploy to Github Package Registry
        #env:
          #USER_NAME: ${{ secrets.USER_NAME }}
          #TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        #run: mvn --settings settings.xml --file pom.xml deploy
        #run: mvn --batch-mode --update-snapshots package

#****************************************************************
  
  publish-artifact:
    runs-on: ubuntu-latest
    #needs: [unit-test] 
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Maven Settings for deploy
        uses: s4u/maven-settings-action@v2.1.1
      - name: Publish package
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: mvn deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/juandiaz9102/micro-service'
  
##########################################################################  
                                                                        # Docker no tiene error
  Docker:
    name: push Docker image
    runs-on: ubuntu-latest
   
    permissions:
      packages: write
      contents: read
    steps:
      - name: Ckeck out repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USSER_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      #- name: Build and push
        #run: docker build -t juandiaz9102/image-nginx:tag .

      #- run: docker push juandiaz9102/image-nginx:tag


  